spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:scheme-default_emotion.sql
      data-locations: classpath:data-comment.sql, classpath:data-default_emotion.sql
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.id}
            client-secret: ${google.secret}
            redirect-uri: ${google.redirectUrl}
            scope:
              - email
              - profile
#          kakao:
#            client-id: ${kakao.id}
#            client-secret: ${kakao.secret}
#            #redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#            redirect-uri: https://getpostman.com/oauth2/callback
#            authorization-grant-type: authorization_code
#            client-authentication-method: POST
#            client-name: Kakao
#            scope:
#              - profile_nickname
          naver:
            client-id: ${naver.id}
            client-secret: ${naver.secret}
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: ${naver.redirectUrl}



        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


jwt:
  issuer: gisu1102@gmail.com
  secret_key: ${jwt.secret_key}
