spring:
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.h2.Driver
    url : 'jdbc:h2:~/test'
    hikari:
      username: sa
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true