spring:
  datasource:
    driver-class-name: org.h2.Driver
    url : 'jdbc:h2:~/test'
    hikari:
      username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1079251988633-iudjltvvh942nads7gc1jpqkfp7l5gp5.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
          kakao:
            client-id: 4fd9c148291848dd3f2769521cb9e245
            client-secret: PEavDY9bnkmtmCKjb1vrtgOqKIEjhnsA
            #redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            redirect-uri: https://getpostman.com/oauth2/callback
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
          naver:
            client-id: snAMYKl4CmYZAIu2j_S_
            client-secret: LTvu56BMd8
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver



        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


jwt:
  issuer: gisu1102@gmail.com
  secret_key: emolog