spring:
  datasource:
    url: ${DB.url}
    username: ${DB.username}
    password : ${DB.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:scheme-default_emotion.sql
      data-locations: classpath:data-comment.sql, classpath:data-default_emotion.sql
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.id}
            client-secret: ${google.secret}
            redirect-uri: ${google.redirectUrl}
            scope:
              - email
              - profile
          naver:
            client-id: ${naver.id}
            client-secret: ${naver.secret}
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: ${naver.redirectUrl}
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

jwt:
  issuer: gisu1102@gmail.com
  secret_key: ${jwt.secret_key}

cloud:
  aws:
    credentials:
      access-key: ${aws.s3.access}
      secret-key: ${aws.s3.secret}
    region:
      static: ${aws.s3.region}
    s3:
      bucket: ${aws.s3.bucket}
    stack:
      auto: false